spring:
  profiles:
    active: development
---
server:
  port: 9004
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
  ignored:
    - /signup/**
logging.level.org.springframework.security: DEBUG
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/DESHA_DATABASE
    username: authUser
    password: 123456
    initialize: true
security.ignored: /resources/**
eureka:
  instance:
    non-secure-port: 9004
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9003/eureka/
