---
spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service:
      path: /api/**
      url: http://localhost:9005
    auth-service:
      path: /user/**
      url: http://localhost:9004/uaa/user
    user-service:
      path: /users/**
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://localhost:9004/uaa/user
    client:
      accessTokenUri: http://localhost:9004/uaa/oauth/token
      userAuthorizationUri: http://localhost:9004/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
eureka:
  instance:
    non-secure-port: 9000
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9003/eureka/
