---
spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: proxy
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    auth: /signup/**
    #account-service: /account/**
    #payment-service: /payment/**
    #inventory-service: /inventory/**
    #order-service: /order/**
    #user-service: /user/**
    #catalog-service: /catalog/**
    #shopping-cart-service: /shoppingcart/**
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9004/uaa/user
  ignored: /catalog/**
