---
spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: proxy
zuul:
  ignoredServices: '*'
  routes:
    auth: 
      path: /uaa/signup/**
      stripPrefix: false
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9004/uaa/user
  ignored: /uaa/signup/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9003/eureka/
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
